### ISSUE TITLE
Prism errors in Javascript console when loading solution

### ISSUE THREAD

**Issue by sshine** [exercism/bugs#37]
Looking in the Javascript console while loading the solution to an exercise, I get the following two errors:

```
net::ERR_ABORTED 404 GET https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-text.min.js
net::ERR_ABORTED 404 GET https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/components/prism-plain.min.js
```

I don't know what the implications are.

**Comment by kntsoriano** [comment]
@sshine Thanks for this :) Upon looking into it, it's an error with the prism autoloader we're using. Since we have code blocks that it can't pick up the language of, it marks it as language `plain`, and there are no prism files for the language `plain`.

I think having this is fine and we shouldn't have any problems having this error right now.
